language: python
python:
- '2.7'
install: 'pip install pybuilder '
script: pyb install_dependencies package   -P build_number=0.1.${TRAVIS_BUILD_NUMBER}
deploy:
  provider: pypi
  user: alienvault_engineering
  distributions: sdist
  server: https://upload.pypi.org/legacy/
  password:
    secure: 5zjj1DF8C7ZLABKAnXOz4OO/+VmlCePSyX07i0MzgsfhzOS2fAz8X1GFolKvpCgU0qJfo9zEv59JxCmG6vFs49LY8rc80yCy6ck914MczJelKt/zC3SibM1/Gu3KgwZXFpTbwQBIoqKQvzJqVoTQLcQMuMCHZay3yfVIqtrSCuRUrvmWphPn76Z/LIWiIWshjA56L9f9vPHdflZGm7sJNIs+B+mbbGtt0Ldb8MZeVFTBgqCMcjzk5MlNeHJztj0231VU6FAS06iYqrnE0ehBPd626ZgBwNulCP0xUwW4Xe2Ve96GvHUQ3zLRgHpmAr4XRfQDeby+auOcbHkA7EE+Ov2fVPAjwo8QrifGKFPb8wpnsj5CQlfteI+d7iXDMJwA+13554rnqzi9PphDZoBbWlLMbOpkRGZZ0U0astnweD74HLTZ4ASeS0SctivL3xOA77fYuashorRB7daVOk3DTBqCwAFjv2u6dvoLQqYmABkIzgMfhbu1c+kjg1aKV1QtEmBG9ziqo+DSo+YDvTJrQoeduzeqzkRBhmx2Wwr5tvFknYU3tYWu/Xva8NbgX1qsxx7dxxC9UO+QgYk9oSJKqtLtRhnLuC0wqTWEEUGC6p8oWgXCEw3W6+8na1OPG5WwH+w0eUMqIYgujH/hW+GqVv+U9C5HJS+MINzrshl5jWU=
